### PR TITLE
Feature/snap scroll

### PR DESCRIPTION
**Pull request by marijnschilling**
Snappy scrolly 

I implemented all this custom contentOffset setting stuff in the scrollview delegates, if you know an easier way just let me know!

And here's a gif: but you kinda just have to feel how it works. Feels good. If it works well i'm also gonna implement this on the vertical transition.
snappyscrolly

### CODE REVIEW

**Comment by 3lvis** [comment]
The snap feels pretty smooth! 🚀

**Comment by 3lvis** [comment]
I think we could improve fast dragging, have you noticed that when you drag fast between left and right it doesn't follow the strength of the dragging?

**Comment by marijnschilling** [comment]
It's becausethe setting of the contentOfset happens in `scrollViewWillBeginDecelerating` which is called too soon..

I should set it on `scrollViewDidEndDragging` I think, but when the scroll has a velocity the contentOffset is just not being set, seems like the current scroll movement is overwritting the setting of the contentOfset. So I think this is the best solution...

**Comment by 3lvis** [comment]
I see the problem now!!! You need to use the `velocity` from `scrollViewWillEndDragging`. How? I'm not sure. 🤔

**Comment by marijnschilling** [comment]
Yeah, the problem is that setting the contentOffset there when the velocity is not 0 does not work.

**Comment by 3lvis** [comment]
@marijnschilling check https://github.com/3lvis/PaginatedScrollView there horizontal pagination is working just fine.

**Comment by marijnschilling** [comment]
Ooh that looks really good actually! I might just need to rewrite it and implement it all like that. Also looks good that i takes page loading into account. Mine would just have all the pages loaded at once atm. 

What do you think? Should i just kinda copy that? Because i can't ad a cartfile to my framework right?

**Comment by 3lvis** [comment]
@marijnschilling copying sounds perfect to me. 👌

**Comment by marijnschilling** [comment]
💥 @elvis used the code from paginatedScrollView. I plan on using the same for the vertical scroll!

**Comment by 3lvis** [comment]
@marijnschilling much better! Ship it 👏

**Review by 3lvis — APPROVED** [review]

**Pull request merged**
