### PR TITLE
Navigation collection view

### PR DESCRIPTION
**Pull request by marijnschilling**
navigation
👀

### CODE REVIEW

**Comment by 3lvis** [comment]
giphy 7

**Comment by marijnschilling** [comment]
Is that @3lvis for ship it? 🚣

**Comment by 3lvis** [comment]
@marijnschilling that was a "Damn girl", haha. Reading the code now.

**Comment by 3lvis** [comment]
Looks good, @marijnschilling! Ship it!

**Review by 3lvis — APPROVED** [review]

**Pull request merged**
